version: "3"
services:
  redis:
    container_name: "redis"
    image: redis
    ports: 
      - "6379"
  nginx:
    container_name: "nginx"
    restart: always
    build:
      context: ./nginx
    ports: 
      - "80:80" 
  client:
    container_name: "client"
    build: 
      context: ./client
    ports: 
      - "5000"
  mongo:
    container_name: "mongodb"
    image: mongo
    ports:
      - "27017"
  auth:
    depends_on: 
      - mongo
    container_name: "auth"
    build: 
      context: ./back/auth
    ports: 
      - "8100"
  service-form:
    depends_on: 
      - mongo
    container_name: "service-form"
    build:
      context: ./back/service-form
    ports:
      - "8300"
  service-formula:
    depends_on: 
      - mongo
    container_name: "service-formula"
    build: 
      context: ./back/service-formula
    ports: 
      - "8400"
  service-project:
    depends_on: 
      - mongo
    container_name: "service-project"
    build:
      context: ./back/service-project
    ports: 
      - "8000"
    